### ISSUE TITLE
How would I use a custom dictionary?

### ISSUE THREAD

**Issue by tleyden** [GeertJohan/go.tesseract#3]
In the Tesseract FAQ they mention the ability to use a custom dictionary:

https://code.google.com/p/tesseract-ocr/wiki/FAQ#How_do_I_provide_my_own_dictionary?

Is this ability exposed in go-tesseract?  Any pointers on how to actually do it?

**Comment by JonyGreen3** [comment]
I'm not a developer, I always use this free <a href="http://www.online-code.net/ocr.html">online ocr</a> servie.
