### ISSUE TITLE
Create gopkg.in compatible branches

### ISSUE THREAD

**Issue by robertmeta** [GeertJohan/go.tesseract#9]
http://labix.org/gopkg.in has a nice system for stable versions of Go projects.  Creating gopkg compatible branches has two advantages.  

1. Make your project compatibility with gopkg (obviously)
2. Makes it clear that you care about backwards compatibility on your project, a strong signal for contributors.

Specific to go.leptonica and go.tesseract, it also makes it easy for them to depend on each other while continuing to get bug fixes and progress.  go.tesseract v1 would depend on go.leptonica v1 and so forth.  Then, if breaking changes had to be made, you spin up v2 of each without damaging the stable v1 branches and this all works with standard go get.

**Comment by GeertJohan** [comment]
Closing this issue as leptonica and tesseract now have gopkg.in URL's.
I might move to go-tesseract organization later if breaking changes need to be made.
